/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using TMS.Services.Models.SwaggerModels;
using TMS.Services.Client;

namespace TMS.Services.SOFClientAPIs
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAccountsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>AccountBalanceResponseModel</returns>
        AccountBalanceResponseModel ApiAccountsAccountIdBalancesBalanceTypeIdGet (int? accountId, int? balanceTypeId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>ApiResponse of AccountBalanceResponseModel</returns>
        ApiResponse<AccountBalanceResponseModel> ApiAccountsAccountIdBalancesBalanceTypeIdGetWithHttpInfo (int? accountId, int? balanceTypeId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        void ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostWithHttpInfo (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns></returns>
        void ApiAccountsAccountIdRequestsRequestIdDelete (int? accountId, int? requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiAccountsAccountIdRequestsRequestIdDeleteWithHttpInfo (int? accountId, int? requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns></returns>
        void ApiAccountsAccountIdRequestsRequestIdPut (int? accountId, int? requestId, List<int?> transactionIds = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiAccountsAccountIdRequestsRequestIdPutWithHttpInfo (int? accountId, int? requestId, List<int?> transactionIds = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns></returns>
        void ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost (int? fromAccountId, int? toAccountId, int? requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostWithHttpInfo (int? fromAccountId, int? toAccountId, int? requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns></returns>
        void ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns></returns>
        void ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut (int? fromAccountId, int? toAccountId, double? amount);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>Task of AccountBalanceResponseModel</returns>
        System.Threading.Tasks.Task<AccountBalanceResponseModel> ApiAccountsAccountIdBalancesBalanceTypeIdGetAsync (int? accountId, int? balanceTypeId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>Task of ApiResponse (AccountBalanceResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountBalanceResponseModel>> ApiAccountsAccountIdBalancesBalanceTypeIdGetAsyncWithHttpInfo (int? accountId, int? balanceTypeId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostAsync (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostAsyncWithHttpInfo (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiAccountsAccountIdRequestsRequestIdDeleteAsync (int? accountId, int? requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsAccountIdRequestsRequestIdDeleteAsyncWithHttpInfo (int? accountId, int? requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiAccountsAccountIdRequestsRequestIdPutAsync (int? accountId, int? requestId, List<int?> transactionIds = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsAccountIdRequestsRequestIdPutAsyncWithHttpInfo (int? accountId, int? requestId, List<int?> transactionIds = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostAsync (int? fromAccountId, int? toAccountId, int? requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostAsyncWithHttpInfo (int? fromAccountId, int? toAccountId, int? requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostAsync (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostAsyncWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutAsync (int? fromAccountId, int? toAccountId, double? amount);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutAsyncWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AccountsApi : IAccountsApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountsApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class
        /// </summary>
        /// <returns></returns>
        public AccountsApi()
        {
            this.Configuration = Configuration.Default;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>AccountBalanceResponseModel</returns>
        public AccountBalanceResponseModel ApiAccountsAccountIdBalancesBalanceTypeIdGet (int? accountId, int? balanceTypeId)
        {
             ApiResponse<AccountBalanceResponseModel> localVarResponse = ApiAccountsAccountIdBalancesBalanceTypeIdGetWithHttpInfo(accountId, balanceTypeId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>ApiResponse of AccountBalanceResponseModel</returns>
        public ApiResponse< AccountBalanceResponseModel > ApiAccountsAccountIdBalancesBalanceTypeIdGetWithHttpInfo (int? accountId, int? balanceTypeId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdGet");
            // verify the required parameter 'balanceTypeId' is set
            if (balanceTypeId == null)
                throw new ApiException(400, "Missing required parameter 'balanceTypeId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdGet");

            var localVarPath = "/api/Accounts/{accountId}/balances/{balanceTypeId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (balanceTypeId != null) localVarPathParams.Add("balanceTypeId", this.Configuration.ApiClient.ParameterToString(balanceTypeId)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdBalancesBalanceTypeIdGet", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<AccountBalanceResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AccountBalanceResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountBalanceResponseModel)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>Task of AccountBalanceResponseModel</returns>
        public async System.Threading.Tasks.Task<AccountBalanceResponseModel> ApiAccountsAccountIdBalancesBalanceTypeIdGetAsync (int? accountId, int? balanceTypeId)
        {
             ApiResponse<AccountBalanceResponseModel> localVarResponse = await ApiAccountsAccountIdBalancesBalanceTypeIdGetAsyncWithHttpInfo(accountId, balanceTypeId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="balanceTypeId"></param>
        /// <returns>Task of ApiResponse (AccountBalanceResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AccountBalanceResponseModel>> ApiAccountsAccountIdBalancesBalanceTypeIdGetAsyncWithHttpInfo (int? accountId, int? balanceTypeId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdGet");
            // verify the required parameter 'balanceTypeId' is set
            if (balanceTypeId == null)
                throw new ApiException(400, "Missing required parameter 'balanceTypeId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdGet");

            var localVarPath = "/api/Accounts/{accountId}/balances/{balanceTypeId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (balanceTypeId != null) localVarPathParams.Add("balanceTypeId", this.Configuration.ApiClient.ParameterToString(balanceTypeId)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdBalancesBalanceTypeIdGet", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<AccountBalanceResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AccountBalanceResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountBalanceResponseModel)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        public void ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null)
        {
             ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostWithHttpInfo(accountId, requestId, balanceTypeId, body);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostWithHttpInfo (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost");
            // verify the required parameter 'balanceTypeId' is set
            if (balanceTypeId == null)
                throw new ApiException(400, "Missing required parameter 'balanceTypeId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost");

            var localVarPath = "/api/Accounts/{accountId}/balances/{balanceTypeId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            if (balanceTypeId != null) localVarPathParams.Add("balanceTypeId", this.Configuration.ApiClient.ParameterToString(balanceTypeId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost", localVarResponse);
                ////if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostAsync (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null)
        {
             await ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostAsyncWithHttpInfo(accountId, requestId, balanceTypeId, body);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="balanceTypeId"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPostAsyncWithHttpInfo (int? accountId, int? requestId, int? balanceTypeId, HoldBalanceModel body = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost");
            // verify the required parameter 'balanceTypeId' is set
            if (balanceTypeId == null)
                throw new ApiException(400, "Missing required parameter 'balanceTypeId' when calling AccountsApi->ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost");

            var localVarPath = "/api/Accounts/{accountId}/balances/{balanceTypeId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            if (balanceTypeId != null) localVarPathParams.Add("balanceTypeId", this.Configuration.ApiClient.ParameterToString(balanceTypeId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdBalancesBalanceTypeIdRequestsRequestIdPost", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns></returns>
        public void ApiAccountsAccountIdRequestsRequestIdDelete (int? accountId, int? requestId)
        {
             ApiAccountsAccountIdRequestsRequestIdDeleteWithHttpInfo(accountId, requestId);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ApiAccountsAccountIdRequestsRequestIdDeleteWithHttpInfo (int? accountId, int? requestId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdDelete");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdDelete");

            var localVarPath = "/api/Accounts/{accountId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdRequestsRequestIdDelete", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiAccountsAccountIdRequestsRequestIdDeleteAsync (int? accountId, int? requestId)
        {
             await ApiAccountsAccountIdRequestsRequestIdDeleteAsyncWithHttpInfo(accountId, requestId);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsAccountIdRequestsRequestIdDeleteAsyncWithHttpInfo (int? accountId, int? requestId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdDelete");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdDelete");

            var localVarPath = "/api/Accounts/{accountId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdRequestsRequestIdDelete", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns></returns>
        public void ApiAccountsAccountIdRequestsRequestIdPut (int? accountId, int? requestId, List<int?> transactionIds = null)
        {
             ApiAccountsAccountIdRequestsRequestIdPutWithHttpInfo(accountId, requestId, transactionIds);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ApiAccountsAccountIdRequestsRequestIdPutWithHttpInfo (int? accountId, int? requestId, List<int?> transactionIds = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdPut");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdPut");

            var localVarPath = "/api/Accounts/{accountId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            if (transactionIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "transactionIds", transactionIds)); // query parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdRequestsRequestIdPut", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiAccountsAccountIdRequestsRequestIdPutAsync (int? accountId, int? requestId, List<int?> transactionIds = null)
        {
             await ApiAccountsAccountIdRequestsRequestIdPutAsyncWithHttpInfo(accountId, requestId, transactionIds);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="requestId"></param>
        /// <param name="transactionIds"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsAccountIdRequestsRequestIdPutAsyncWithHttpInfo (int? accountId, int? requestId, List<int?> transactionIds = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdPut");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsAccountIdRequestsRequestIdPut");

            var localVarPath = "/api/Accounts/{accountId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("accountId", this.Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            if (transactionIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "transactionIds", transactionIds)); // query parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsAccountIdRequestsRequestIdPut", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns></returns>
        public void ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost (int? fromAccountId, int? toAccountId, int? requestId)
        {
             ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostWithHttpInfo(fromAccountId, toAccountId, requestId);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostWithHttpInfo (int? fromAccountId, int? toAccountId, int? requestId)
        {
            // verify the required parameter 'fromAccountId' is set
            if (fromAccountId == null)
                throw new ApiException(400, "Missing required parameter 'fromAccountId' when calling AccountsApi->ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost");
            // verify the required parameter 'toAccountId' is set
            if (toAccountId == null)
                throw new ApiException(400, "Missing required parameter 'toAccountId' when calling AccountsApi->ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost");

            var localVarPath = "/api/Accounts/ConfirmTransfer/{fromAccountId}/{toAccountId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fromAccountId != null) localVarPathParams.Add("fromAccountId", this.Configuration.ApiClient.ParameterToString(fromAccountId)); // path parameter
            if (toAccountId != null) localVarPathParams.Add("toAccountId", this.Configuration.ApiClient.ParameterToString(toAccountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostAsync (int? fromAccountId, int? toAccountId, int? requestId)
        {
             await ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostAsyncWithHttpInfo(fromAccountId, toAccountId, requestId);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPostAsyncWithHttpInfo (int? fromAccountId, int? toAccountId, int? requestId)
        {
            // verify the required parameter 'fromAccountId' is set
            if (fromAccountId == null)
                throw new ApiException(400, "Missing required parameter 'fromAccountId' when calling AccountsApi->ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost");
            // verify the required parameter 'toAccountId' is set
            if (toAccountId == null)
                throw new ApiException(400, "Missing required parameter 'toAccountId' when calling AccountsApi->ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost");
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling AccountsApi->ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost");

            var localVarPath = "/api/Accounts/ConfirmTransfer/{fromAccountId}/{toAccountId}/requests/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fromAccountId != null) localVarPathParams.Add("fromAccountId", this.Configuration.ApiClient.ParameterToString(fromAccountId)); // path parameter
            if (toAccountId != null) localVarPathParams.Add("toAccountId", this.Configuration.ApiClient.ParameterToString(toAccountId)); // path parameter
            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsConfirmTransferFromAccountIdToAccountIdRequestsRequestIdPost", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns></returns>
        public void ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType)
        {
             ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostWithHttpInfo(fromAccountId, toAccountId, amount, transactionType);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType)
        {
            // verify the required parameter 'fromAccountId' is set
            if (fromAccountId == null)
                throw new ApiException(400, "Missing required parameter 'fromAccountId' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");
            // verify the required parameter 'toAccountId' is set
            if (toAccountId == null)
                throw new ApiException(400, "Missing required parameter 'toAccountId' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");
            // verify the required parameter 'transactionType' is set
            if (transactionType == null)
                throw new ApiException(400, "Missing required parameter 'transactionType' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");

            var localVarPath = "/api/Accounts/ManageBalance/{fromAccountId}/{toAccountId}/balances/{amount}/{transactionType}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fromAccountId != null) localVarPathParams.Add("fromAccountId", this.Configuration.ApiClient.ParameterToString(fromAccountId)); // path parameter
            if (toAccountId != null) localVarPathParams.Add("toAccountId", this.Configuration.ApiClient.ParameterToString(toAccountId)); // path parameter
            if (amount != null) localVarPathParams.Add("amount", this.Configuration.ApiClient.ParameterToString(amount)); // path parameter
            if (transactionType != null) localVarPathParams.Add("transactionType", this.Configuration.ApiClient.ParameterToString(transactionType)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostAsync (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType)
        {
             await ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostAsyncWithHttpInfo(fromAccountId, toAccountId, amount, transactionType);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <param name="transactionType"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePostAsyncWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount, TransactionType transactionType)
        {
            // verify the required parameter 'fromAccountId' is set
            if (fromAccountId == null)
                throw new ApiException(400, "Missing required parameter 'fromAccountId' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");
            // verify the required parameter 'toAccountId' is set
            if (toAccountId == null)
                throw new ApiException(400, "Missing required parameter 'toAccountId' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");
            // verify the required parameter 'transactionType' is set
            if (transactionType == null)
                throw new ApiException(400, "Missing required parameter 'transactionType' when calling AccountsApi->ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost");

            var localVarPath = "/api/Accounts/ManageBalance/{fromAccountId}/{toAccountId}/balances/{amount}/{transactionType}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fromAccountId != null) localVarPathParams.Add("fromAccountId", this.Configuration.ApiClient.ParameterToString(fromAccountId)); // path parameter
            if (toAccountId != null) localVarPathParams.Add("toAccountId", this.Configuration.ApiClient.ParameterToString(toAccountId)); // path parameter
            if (amount != null) localVarPathParams.Add("amount", this.Configuration.ApiClient.ParameterToString(amount)); // path parameter
            if (transactionType != null) localVarPathParams.Add("transactionType", this.Configuration.ApiClient.ParameterToString(transactionType)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsManageBalanceFromAccountIdToAccountIdBalancesAmountTransactionTypePost", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns></returns>
        public void ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut (int? fromAccountId, int? toAccountId, double? amount)
        {
             ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutWithHttpInfo(fromAccountId, toAccountId, amount);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount)
        {
            // verify the required parameter 'fromAccountId' is set
            if (fromAccountId == null)
                throw new ApiException(400, "Missing required parameter 'fromAccountId' when calling AccountsApi->ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut");
            // verify the required parameter 'toAccountId' is set
            if (toAccountId == null)
                throw new ApiException(400, "Missing required parameter 'toAccountId' when calling AccountsApi->ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut");
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling AccountsApi->ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut");

            var localVarPath = "/api/Accounts/ReturnBalance/{fromAccountId}/{toAccountId}/balances/{amount}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fromAccountId != null) localVarPathParams.Add("fromAccountId", this.Configuration.ApiClient.ParameterToString(fromAccountId)); // path parameter
            if (toAccountId != null) localVarPathParams.Add("toAccountId", this.Configuration.ApiClient.ParameterToString(toAccountId)); // path parameter
            if (amount != null) localVarPathParams.Add("amount", this.Configuration.ApiClient.ParameterToString(amount)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutAsync (int? fromAccountId, int? toAccountId, double? amount)
        {
             await ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutAsyncWithHttpInfo(fromAccountId, toAccountId, amount);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="fromAccountId"></param>
        /// <param name="toAccountId"></param>
        /// <param name="amount"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPutAsyncWithHttpInfo (int? fromAccountId, int? toAccountId, double? amount)
        {
            // verify the required parameter 'fromAccountId' is set
            if (fromAccountId == null)
                throw new ApiException(400, "Missing required parameter 'fromAccountId' when calling AccountsApi->ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut");
            // verify the required parameter 'toAccountId' is set
            if (toAccountId == null)
                throw new ApiException(400, "Missing required parameter 'toAccountId' when calling AccountsApi->ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut");
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling AccountsApi->ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut");

            var localVarPath = "/api/Accounts/ReturnBalance/{fromAccountId}/{toAccountId}/balances/{amount}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fromAccountId != null) localVarPathParams.Add("fromAccountId", this.Configuration.ApiClient.ParameterToString(fromAccountId)); // path parameter
            if (toAccountId != null) localVarPathParams.Add("toAccountId", this.Configuration.ApiClient.ParameterToString(toAccountId)); // path parameter
            if (amount != null) localVarPathParams.Add("amount", this.Configuration.ApiClient.ParameterToString(amount)); // path parameter
            // authentication (Bearer) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAccountsReturnBalanceFromAccountIdToAccountIdBalancesAmountPut", localVarResponse);
                //if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

    }
}
